-- MySQL Script generated by MySQL Workbench
-- Sat 15 Jun 2019 12:04:49 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GCDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GCDB` ;

-- -----------------------------------------------------
-- Schema GCDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GCDB` DEFAULT CHARACTER SET latin1 ;
USE `GCDB` ;

-- -----------------------------------------------------
-- Table `GCDB`.`LAUNCH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GCDB`.`LAUNCH` ;

CREATE TABLE IF NOT EXISTS `GCDB`.`LAUNCH` (
  `l_id` INT(11) NOT NULL AUTO_INCREMENT,
  `l_date` DATETIME NULL DEFAULT NULL,
  `l_description` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`l_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GCDB`.`TELEMETRY_NOSECONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GCDB`.`TELEMETRY_NOSECONE` ;

CREATE TABLE IF NOT EXISTS `GCDB`.`TELEMETRY_NOSECONE` (
  `tn_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tn_lid` INT(11) NOT NULL,
  `tn_timestamp` DATETIME NULL DEFAULT NULL,
  `tn_timeoftransmission` FLOAT NULL DEFAULT NULL,
  `tn_altitude` FLOAT NULL DEFAULT NULL,
  `tn_GPSaltitude` FLOAT NULL DEFAULT NULL,
  `tn_GPSspeed` FLOAT NULL DEFAULT NULL,
  `tn_GPSx` FLOAT NULL DEFAULT NULL,
  `tn_GPSy` FLOAT NULL DEFAULT NULL,
  `tn_batteryvoltage` FLOAT NULL DEFAULT NULL,
  `tn_internaltemp` FLOAT NULL DEFAULT NULL,
  `tn_separation` TINYINT(4) NULL DEFAULT NULL,
  `tn_signal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tn_id`),
  INDEX `fk_TELEMETRY_NOSECONE_ToLAUNCH_idx` (`tn_lid` ASC) VISIBLE,
  CONSTRAINT `fk_TELEMETRY_NOSECONE_ToLAUNCH`
    FOREIGN KEY (`tn_lid`)
    REFERENCES `GCDB`.`LAUNCH` (`l_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 350
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GCDB`.`TELEMETRY_VEHICLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GCDB`.`TELEMETRY_VEHICLE` ;

CREATE TABLE IF NOT EXISTS `GCDB`.`TELEMETRY_VEHICLE` (
  `tv_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tv_lid` INT(11) NOT NULL,
  `tv_timestamp` DATETIME NULL DEFAULT NULL,
  `tv_timeoftransmission` FLOAT NULL DEFAULT NULL,
  `tv_altitude` FLOAT NULL DEFAULT NULL,
  `tv_speed` FLOAT NULL DEFAULT NULL,
  `tv_acceleration` FLOAT NULL DEFAULT NULL,
  `tv_GPSx` FLOAT NULL DEFAULT NULL,
  `tv_GPSy` FLOAT NULL DEFAULT NULL,
  `tv_batteryvoltage` FLOAT NULL DEFAULT NULL,
  `tv_internaltemp` FLOAT NULL DEFAULT NULL,
  `tv_separation` TINYINT(4) NULL DEFAULT NULL,
  `tv_signal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tv_id`),
  INDEX `fk_TELEMETRY_VEHICLE_ToLaunch_idx` (`tv_lid` ASC) VISIBLE,
  CONSTRAINT `fk_TELEMETRY_VEHICLE_ToLaunch`
    FOREIGN KEY (`tv_lid`)
    REFERENCES `GCDB`.`LAUNCH` (`l_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1922
DEFAULT CHARACTER SET = latin1;

USE `GCDB` ;

-- -----------------------------------------------------
-- procedure usp_AddLaunch
-- -----------------------------------------------------

USE `GCDB`;
DROP procedure IF EXISTS `GCDB`.`usp_AddLaunch`;

DELIMITER $$
USE `GCDB`$$
CREATE DEFINER=`webuser`@`%` PROCEDURE `usp_AddLaunch`(descr VARCHAR(250))
BEGIN

INSERT INTO LAUNCH(	l_date,
                    l_description)
VALUES(NOW(), descr);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_AddTelemetry_Nosecone
-- -----------------------------------------------------

USE `GCDB`;
DROP procedure IF EXISTS `GCDB`.`usp_AddTelemetry_Nosecone`;

DELIMITER $$
USE `GCDB`$$
CREATE DEFINER=`webuser`@`%` PROCEDURE `usp_AddTelemetry_Nosecone`(launchID INT, timeoftransmission FLOAT, altitude FLOAT, GPSaltitude FLOAT, GPSspeed FLOAT, GPSx FLOAT, GPSy FLOAT, battery FLOAT, temperature FLOAT, separation TINYINT, signalStrength INT)
BEGIN
	INSERT INTO TELEMETRY_NOSECONE(tn_lid, tn_timestamp, tn_timeoftransmission, tn_altitude, tn_GPSaltitude, tn_GPSspeed, tn_GPSx, tn_GPSy, tn_batteryvoltage, tn_internaltemp, tn_separation, tn_signal)
    VALUES
    (launchID, NOW(), timeoftransmission, altitude, GPSaltitude, GPSspeed, GPSx, GPSy, battery, temperature, separation, signalStrength);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_AddTelemetry_Vehicle
-- -----------------------------------------------------

USE `GCDB`;
DROP procedure IF EXISTS `GCDB`.`usp_AddTelemetry_Vehicle`;

DELIMITER $$
USE `GCDB`$$
CREATE DEFINER=`webuser`@`%` PROCEDURE `usp_AddTelemetry_Vehicle`(launchID INT, timeoftransmission FLOAT, altitutde FLOAT, speed FLOAT, acceleration FLOAT, GPSx FLOAT, GPSy FLOAT, voltage FLOAT, temperature FLOAT, separation TINYINT(4), signalStrength INT)
BEGIN
	INSERT INTO TELEMETRY_VEHICLE(tv_lid, tv_timestamp, tv_timeoftransmission, tv_altitude, tv_speed, tv_acceleration, tv_GPSx, tv_GPSy,  tv_batteryvoltage, tv_internaltemp, tv_separation, tv_signal)
    VALUES
    (launchID, NOW(), timeoftransmission, altitutde, speed, acceleration, GPSx, GPSy, voltage, temperature, separation, signalStrength);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
